name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t my-java-app .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'deeptidocker11/my-java-app:latest'
        format: sarif
        output: trivy-results.sarif
        scan-type: image
        scan-ref: .
        ignore-unfixed: false
        vuln-type: os,library
        severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
        list-all-pkgs: false

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'   
    
    - name: Log in to Docker Hub
      run: docker login -u "${{ secrets.docker_username }}" -p "${{ secrets.docker_sec1 }}"

    - name: Tag Docker image
      run: docker tag my-java-app "${{ secrets.docker_username }}/my-java-app:latest"

    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.docker_username }}/my-java-app:latest"

