name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t my-java-app .

   # Pull the Trivy Docker image
    - name: Pull Trivy Docker image
      run: docker pull aquasec/trivy

   # Run Trivy to scan the Docker image
    - name: Run Trivy vulnerability scanner
      run: |
        docker run --rm aquasec/trivy deeptidocker11/javaprogram1:myjavaimage

    # Upload Trivy scan results to GitHub Security tab
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Log in to Docker Hub
      run: docker login -u "${{ secrets.docker_username }}" -p "${{ secrets.docker_sec1 }}"

    - name: Tag Docker image
      run: docker tag my-java-app "${{ secrets.docker_username }}/my-java-app:latest"

    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.docker_username}}/my-java-app:latest"

      
      
      
      
